### ISSUE TITLE
how to install supervisor-py3k

### ISSUE THREAD

**Issue by sbmzhcn** [palmkevin/supervisor-py3k#1]
python setup.py install
Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.4.2 (default, Jan 14 2015, 19:06:59) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)].  Please install using a supported version.

How to ???????????????????????????

**Comment by palmkevin** [comment]
At the time my focus was on making it running on python 3. I never had a look at the setup.py. Probably the dependency to py2 is still in there.
I you want to use the branch, just download it and extract the supervisor folder in a folder that is in your PYTHONPATH.
However, I would recommend to NOT use my branch at all, but to use the original branch from supervisor. They made quite some progress in supporting py3.
